server:
  port: 18086
spring:
  application:
    name: search-web
  thymeleaf:
    cache: false
  main:
    allow-bean-definition-overriding: true



eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true

feign:
  httpclient:
    connection-timeout: 6000
  hystrix:
    enabled: true

#ribbon的超时时间
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000